### ISSUE TITLE
Feature to transform Json to Class

### ISSUE THREAD

**Issue by Roldanhollow** [joiful-ts/joiful#141]
Hi there!
Probably I haven't found the possibility to transform a Json into Class after verify if the Json is a valid one.
Just in case this feature is not included ¿Are you guys planning to add it?

**Comment by laurence-myers** [comment]
No plans. The problem is that `joiful` can validate objects okay, but I can't think of a safe way to copy the data into a class instance automatically. If we do it dynamically, you could end up with uninitialised properties, if the class has more properties than the plain object.

The best way I can think would be, in your app code, after validating the plain object (perhaps in your web layer), pass the object to the class constructor and manually set every property. Boring boilerplate code, but type safe. You could avoid the boilerplate by just assigning the plain object to a single property on your "wrapper" class.

Hope that all makes sense.

**Comment by codeandcats** [comment]
Because there's no trivial or elegant method that works well for all circumstances, I would strongly suggest questioning whether you really need to convert your plain-old javascript object into an class instance at all.

From a typing perspective TypeScript will not care if a POJO isn't actually an instance of a class or not so long as the interface is compatible with that of the class (i.e. it has the same fields). It will really only matter if you're doing things like using the `instanceof` operator against it, looking at it's prototype, etc. Hope this helps.

**Comment by gitSambhal** [comment]
@Roldanhollow You can use `plainToClass` method of `class-tranformer` package. 
https://github.com/typestack/class-transformer#plaintoclass
