### ISSUE TITLE
reflect-metadata should be a dependency, not a devDependency

### ISSUE THREAD

**Issue by ujwal-setlur** [joiful-ts/joiful#191]
``reflect-metadata`` should be in ``dependencies`` section of ``package.json`` vs ``devDependencies``. ``reflect-metadata`` is imported in ``src/core.ts`` which makes it a direct dependency. This will break the build of any project that depends on ``joiful``, but otherwise does not depend on ``reflect-metadata``.

**Comment by laurence-myers** [comment]
I agree that it shouldn't be a `devDependency`, if it's imported or used anywhere in `src/*`.

I think, rather than a regular dependency, it should be a "peer dependency": https://classic.yarnpkg.com/en/docs/dependency-types/#toc-peerdependencies

My experience with `reflect-metadata` is that it needs to be imported from the entrypoint of your application. If you don't, there can be issues where there's multiple global metadata containers/singletons. (That was my experience a few years ago, no idea if that's correct/holds up now.)

So, apps that have a dependency on `joiful` also need to have a depency on `reflect-metadata`, and import it somewhere in the app - we shouldn't import & initialise `reflect-metadata` within `joiful`.

**Comment by codeandcats** [comment]
Thanks for bringing this to our attention @ujwal-setlur 👍 

Joiful v3.0.1 now includes `reflect-metadata` as a peer dependency.

**Comment by ujwal-setlur** [comment]
@laurence-myers, @codeandcats, ok , if this is made a peer dependency, I am OK with that. [MikroORM](https://mikro-orm.io), which I also use for my backend services, for example, uses this approach. But it needs to be explicitly called out in the documentation, because otherwise my frontend project does not depend on reflect-metadata. Thanks!

**Comment by ujwal-setlur** [comment]
Looks like MikroORM lists it as a dependency:

https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/package.json

**Comment by codeandcats** [comment]
> But it needs to be explicitly called out in the documentation, because otherwise my frontend project does not depend on reflect-metadata

Good point. The documentation now references the need to install `reflect-metadata`. 👍
