### ISSUE TITLE
Importing constraints contained within namespaces can cause issues

### ISSUE THREAD

**Issue by laurence-myers** [joiful-ts/joiful#2]
This code can fail:
```
import Optional = AnyConstraints.Optional;
import { AnyConstraints } from 'tsdv-joi';
```

This code is fine:
```
import { AnyConstraints } from 'tsdv-joi';
const Optional = AnyConstraints.Optional;
```

This can occur when the order of imports changes, which can be caused by "Organise imports" operations in IDEs like IntelliJ IDEA.

A possible fix is to use objects instead of namespaces to contain each type's constraints. That will force the use of the latter syntax.

**Comment by codeandcats** [comment]
Heya Laurence,

I've actually been contemplating creating a PR to do with this as I'm planning on using this excellent library again so I'm glad you raised it.

I hadn't experienced this problem yet (though I'm probably about to). Personally, I'd just love to not have to go via namespaces to access the decorators I want. So I've been wondering if you'd be open to reorganising the exports so that rather than exporting the decorators from namespaces, they're instead exported them directly from their file.

e.g.

`src/constraints/any.ts`

```typescript
export function Optional() : PropertyDecorator {
   ...
}
```

`src/main.ts`

```typescript
export * as AnyConstraints from './constraints/any';
```

This way consumers can import just the function they need:
```typescript
import { Optional } from 'tsdv-joi/contraints/any'; // Yay!
```

While still allowing them to grab everything grouped by type:
```typescript
import { AnyConstraints } from 'tsdv-joi';
```

Technically this *might* be a breaking change if consumers are currently importing `AnyConstraints`, directly from `tsdv-joi/constraints/any` (etc) but given you export those from `tsdv-joi`, I believe(?) most consumers will be importing from `tsdv-joi` anyway.

It should take of this issue and will result in slightly less friction for the consumer so I in my (very) humble opinion I think it would be worth the major version bump! 🙏 😃

**Comment by laurence-myers** [comment]
Sounds great! A PR would be welcome. :+1: 

(FYI, I've prototyped an alternative approach to derive a type from a Joi schema with just a little bit of wrapping logic, using TypeScript's mapped types. I'd be interested to see what you think.)

**Comment by codeandcats** [comment]
Awesome, thank you! I'll have a fork it and submit a PR in the next couple days.

Ooooh sounds interesting, I'd love to check it out! 😃

Btw, have you seen/started using the [Conditional Types](https://blogs.msdn.microsoft.com/typescript/2018/03/27/announcing-typescript-2-8/#conditional-types) in 2.8? I just recently discovered how to do boolean logic completely in the type system that allows for some really awesome use-cases for mapping types but behind the scenes is hacky AF - now we have proper support for conditional types it should clean it up completely! So excited!

**Comment by laurence-myers** [comment]
I didn't even know TS 2.8 was out. :disappointed: Sounds interesting, I'll have to check it out!

EDIT: And don't thank me, thank you for contributing. :grin:
