### ISSUE TITLE
Make Joi a regular dependency (not a peer dependency)

### ISSUE THREAD

**Issue by laurence-myers** [joiful-ts/joiful#22]
Joi was originally required as a peer dependency, for easier integration with existing codebases that already used Joi. I don't think that provides much value now. Let's just package Joi (and @types/joi) as a regular dependency, and export Joi from tsdv-joi, so that consuming apps don't also need to have their own dependency on Joi (and @types/joi) for constructing schemas for e.g. the `@Items()` decorator.

Relates to #21.

**Comment by codeandcats** [comment]
I was thinking, if we make joi a regular dependency rather than a peer dependency, maybe we should change the `tsdv-joi` API such that you can't simply replace the joi instance (by calling `function registerJoi(customJoi: typeof joi)`), but rather you can only _extend_ the joi that `tsdv-joi` uses. That way, we're not letting the user replace the joi instance with a joi instance that's from an entirely different version to what we're expecting (with potentially different interfaces).

How do we do this? I'm not sure but maybe one or both of below?

- We could simply guide the user into extending rather than outright replacing by changing the wording and signature of our `registerJoi` function to something like `extendJoi(extender: (existingJoi: typeof Joi) => typeof Joi)`
- I believe Joi includes the version of itself on itself so we could check the version of the new joi matches the version of the original joi.

**Comment by laurence-myers** [comment]
Good point! I like your idea of `extendJoi()`. If we give it the same signature as `Joi.extend()`, i.e. it accepts a function that accepts an instance of Joi and returns an extension configuration, we can avoid users injecting a different version of Joi.
