### ISSUE TITLE
Unable to validate an array of strings

### ISSUE THREAD

**Issue by yagyesha** [joiful-ts/joiful#38]
I'm trying to validate an array of strings (i.e. ["abc", "def", "ghi"] ) using something like below:

```
    @NestedArray(String)
    public myArr: Array<string>;
```

But validation fails with error that an object is expected. 

I looked at @Array decorator but it doesn't accept 'type'. 
@Items accepts type but it needs a schema. I could do something like this:

`` @Items(Joi.string()) ``

But i'm trying to avoid exposing **Joi** in my code and work with **tsdv-joi** as much as possible.

Is there any other way to achieve this?

**Comment by codeandcats** [comment]
My two cents: I wouldn’t worry about referencing `joi` in your code.

It’s not like `tsdv-joi` is trying to shield you from the actual library it uses for validation behind the scenes. It’s right there in the name after all. 🙂 So I don’t think have to worry for example that tomorrow `tsdv-joi` will be using something else for validation.

**Comment by yagyesha** [comment]
Understood. However, just curious if this is the expected way to doing array validation?

**Comment by laurence-myers** [comment]
`@Items()` is the expected way to validate array items.

```typescript
class Foo {
    @Items(Joi.string())
    public myArr!: Array<string>;
}
```

Since the `joi` library is a peer dependency, you'll already have it in your project, so it shouldn't be a problem to make use of it alongside `tsdv-joi`.

If you're worried, I think you can import `Joi` from `tsdv-joi/core` (or something like that).

`@NestedArray()` is used to validate objects within an array. You pass in a class whose properties are also decorated by `tsdv-joi`.

```typescript
class Bar {
    @StringSchema()
    public name!: string;
}

class Foo {
    @NestedArray(Bar)
    public myArr: Array<Bar>;
}
```

**Comment by laurence-myers** [comment]
Now that #19 has been merged in, maybe `@Items()` should be changed so it can accept a function, allowing a similar fluent API. This would let you do something like this:

```typescript
class Foo {
    @Items((joi) => joi.string())
    public myArr!: Array<string>;
}
```

**Comment by codeandcats** [comment]
@laurence-myers's suggestion has been merged into master, so it should be in the next release, when it gets released.

**Comment by Sathyanarayanan07** [comment]
How do we use the @items decorator to validate array of string ?I am unable to make this work.

```
class Foo {
    @Items((joi) => joi.string())
    public myArr!: Array<string>;
}
```
I tried the following,

`jf.array().items(string);
`

**Comment by codeandcats** [comment]
Hi @Sathyanarayanan07,

Thank you for your question. The Joiful API has undergone a large change since this issue was originally raised.

You can now validate array properties like so:

```
class Foo {
    @jf.array().items((joi) => joi.string())
    public myArr!: Array<string>;
}
```

Other than looking at the unit tests (which I recommend trying if you get stuck as there are examples for everything), there is no documentation for validating arrays. I will add a todo to add an array example to the README. 🙂

**Comment by codeandcats** [comment]
FYI, I have updated the README now with a couple examples of validating arrays. 😃
