### ISSUE TITLE
CircleCI is not running tests from the "constraints" sub-directory

### ISSUE THREAD

**Issue by laurence-myers** [joiful-ts/joiful#6]
CircleCI is only running 23 tests, instead of 90+ tests. Looks like it's not picking up any tests contained in the "constraints" sub-directory. For some reason this is working locally.

**Comment by codeandcats** [comment]
Not sure why the behaviour would vary based on environment but I have observed in other projects mocha not picking up all tests which was fixed by putting quotes around the path to tests.

E.g. In `package.json` instead of:

```json
"test": "mocha --require source-map-support/register dist/test/**/*.js"
```

Try:

```json
"test": "mocha --require source-map-support/register 'dist/test/**/*.js'"
```

I think without the quotes the shell interprets that arg as a relative path and mangles it.

**Comment by laurence-myers** [comment]
Ah awesome, thanks for looking into this! :grin: 

I think without the quotes, the glob syntax is interpreted/expanded by the command line shell, and with the quotes it's interpreted by mocha.
